config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, :supes, :products, :posts, :events, :comments, :sessions, :user_supes, :user_events, :charges
  resources :cart_products, only: [:create, :destroy]
  resources :purchases, only: [:show, :index]

  get '/home', to: 'users#home', as: 'user_home'
  get '/cart', to: 'users#my_cart', as: 'user_cart'
  post '/comments', to: 'comments#create'
  get '/', to: 'sessions#new', as: 'new_login'
  post '/', to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/confirmation', to: 'purchases#confirmation', as: 'confirmation'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :comments, dependent: :destroy
    has_many :user_supes
    has_many :supes, through: :user_supes
    has_many :user_events, dependent: :destroy 
    has_many :events, through: :user_events

    has_many :comments, dependent: :destroy
    has_many :user_supes, dependent: :destroy
    has_many :supes, through: :user_supes
    has_many :carts
    has_many :products, through: :carts
    has_many :user_events, dependent: :destroy
    has_many :events, through: :user_events

    validates_presence_of :username, :password
    validates_uniqueness_of :username

    def following?(supe)
        self.supes.include?(supe)
    end

    def attending?(event)
        self.events.include?(event)
    end 

    def feed
        Post.all.filter {|post| self.supes.include?(post.supe)}.reverse
    end 

    def cart
        if self.carts.count == 0 || self.carts.last.purchase
            Cart.create(user: self)
        else
            self.carts.last
        end
    end 

    enum role: [:member, :admin]

    after_initialize do
        if self.new_record?
            self.role ||= :member
        end
    end

    def recent_comments
        recent_comments = self.comments.sort_by { |comment| comment.created_at }.reverse
        recent_comments.first(3)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :require_logged_in, only: [:new, :create]


    def index
        @users = User.all
    end

    def home
        @posts = Post.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user_id] = @user.id
            flash[:success] = "Welcome, #{@user.username}"
            redirect_to user_path(@user)
        else
            flash[:my_errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def edit
    end

    def update
        @user.update(user_params)
        if @user.valid?
            flash[:sucess] = "Changes saved!"
            redirect_to user_home_path
        else
            flash[:my_errors] = @user.errors.full_messages
            redirect_to edit_user_path
        end
    end

    def cart
        cart = @user.carts
    end
    

    def destroy 
        @user.destroy 
        redirect_to new_login_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation, :image_url)
    end

    def find_user
        @user = User.find(params[:id])
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit.html.erb
<h1> Update <%= @user.username %>'s Profile here</h1>
<div class="general-container">
    <% if flash[:my_errors] %>
        <% flash[:my_errors].each do |msg| %>
            <p><%= msg %></p>
        <% end %>
    <% end %>


    <%= form_for @user do |f| %>

        <%= f.label :username %>
        <%= f.text_field :username %><br>

        <%= f.label :password %>
        <%= f.password_field :password %><br>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %><br>

        <%= f.label :image_url %>
        <%= f.text_field :image_url %><br>

        <%= f.submit "Save Changes", :class => "edit_user_button"%>
    <% end %>
</div>

app/views/users/home.html.erb
 <% @current_user.feed.each do |post| %>
 <div class="post-container">
    <div class="post-profile-image-cropper">
        <%= link_to supe_path(post.supe) do %>
            <img src="<%= post.supe.image_url %>" class="supe-post-image">
        <% end %>
    </div>
    <div class="post-header">
        <h3 class="poster-name"><%= link_to post.supe.name, supe_path(post.supe) %></h3>
        <div class="post-date">
            <em><%= post.created_at.strftime("%B %d, %Y") %></em>
        </div>
    </div>
    <p class="post-content"><%= post.content %></p>
    
    <% if post.has_media? %>
        <div class="media-container">
            <% if post.has_image? %>
                <%= image_tag(url_for(post.post_file), :class => "post-media") %>
            <% else %>
                <%= video_tag(url_for(post.post_file), size: "640x360", controls: true , :class => "post-media") %>
            <% end %>
        </div> 
    <% end %>   
    
    <div class="stats">
        <div class="likes">
            <%= post.likes%>
            <%= link_to post_path(post), method: :patch do %>
                <img src="<%= asset_path('thumbs-up-icon.png') %>" class="like-button">
            <% end %>
        </div>
        <div class="comments">
            <%= post.comments.count %>
            <%= link_to post_path(post) do %>
                <img src="<%= asset_path('comments-icon.png') %>" class="comment-button">
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/users/my_cart.html.erb
<h1 class="page-header"><%= @current_user.username %>'s Cart </h1>
    <% if @current_user.cart.has_items? %>
        <table class="user-cart-table">
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Edit Item</th>
                <th>Price</th>
            </tr>
            <tr>
                <% @current_user.cart.products.each do |product| %>
                    <% cart_product = CartProduct.find_by(cart_id: @current_user.cart.id, product_id: product.id) %>
                    <td><%= product.name %></td>
                    <td><%= product.description %></td>
                    <td class="item-remove"><%= link_to "Remove", cart_product, :method => :delete %></td>
                    <td>$<%= product.price %></td>
            </tr>
            <% end %>
        </table>
        <% @total = @current_user.cart.products.sum { |product| product.price }%>
            <h3 class="cart-total">Cart Total | $<%= @total %></h3>
        
        <h3 class="buy-merchandise"><%= link_to "Back to Shop!", products_path %></h3>

        <%= form_tag charges_path, id:'chargeForm' do %>
            <% if flash[:error].present? %>
                <div id="error_explanation">
                    <p><%= flash[:error] %></p>
                </div>
            <% end %>
            <%=hidden_field_tag 'stripeToken'%>
            <%=hidden_field_tag 'stripeEmail'%>
            <%=hidden_field_tag 'amount', @total * 100%>
            <%=hidden_field_tag 'customer_name' %>
            <%=hidden_field_tag 'shipping_address' %>
            <%=hidden_field_tag 'cart_id', @current_user.cart.id %>
            <button id="btn-buy" type="button" class="btn btn-success btn-lg btn-block"><span class="glyphicon glyphicon-ok"></span>Buy this!</button>
            
            <script>
                var handler = StripeCheckout.configure({
                    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
                    billingAddress: true,
                    shippingAddress: true,
                    token: function(token, arg) {
                        document.getElementById("stripeToken").value = token.id;
                        document.getElementById("stripeEmail").value = token.email;
                        document.getElementById("customer_name").value = arg.shipping_name;
                        document.getElementById("shipping_address").value = `${arg.shipping_address_line1}, ${arg.shipping_address_city}, ${arg.shipping_address_state} ${arg.shipping_address_zip}`;
                        document.getElementById("chargeForm").submit();
                    }
                });
                document.getElementById('btn-buy').addEventListener('click', function(e) {
                    handler.open({
                        name: 'Purchase Total:',
                        amount: document.getElementById('amount'),
                        description: `$ ${amount.value / 100}`
                    });
                    e.preventDefault();
                })
            </script>
        <% end %>
    <% end %>

app/views/users/new.html.erb
<h1> Welcome!  Create your new account here! </h1>
<div class="general-container">
    <% if flash[:my_errors] %>
        <% flash[:my_errors].each do |msg| %>
            <p><%= msg %></p>
        <% end %>
    <% end %>


    <%= form_for @user, controller: 'users', action: 'create' do |f| %>

        <%= f.label :username %>
        <%= f.text_field :username %><br>

        <%= f.label :password %>
        <%= f.password_field :password %><br>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %><br>

        <%= f.submit "Submit", :class => "new_user_button" %>
    <% end %>
<div>

app/views/users/show.html.erb
<h1 class="profile-page-name"><%= @user.username%>'s Profile Page </h1>
    <h2 class="user-section-titles"> Favorite Supes </h2>
            <% @user.supes.each do |supe| %>
                <div class="index-image-cropper">
                    <%= link_to supe_path(supe) do %>
                        <img src="<%= supe.image_url %>" class="supe-index-image">
                    <% end %>
                </div>
            <% end%>
    <h2 class="user-section-titles"> Upcoming Events for <%= @user.username %> </h2>
        <% if @user.events.any? %>
        <ul>
            <% @user.events.each do |event| %>
            <li class="user-page-events"><%= link_to event.title, event_path(event) %> at <%= event.date.strftime("%B %d, %Y") %> in <%= event.location %></li>
            <% end %>
        </ul>
        <% else %>
            <p><%= @user.username %> hasn't signed up for any events yet!  Go to the events page to see listed events! </p>
        <% end %>
    <h2 class="user-section-titles"> Recent Comments by <%= @user.username %></h2>
        <% if @user.comments.any? %>
            <%  @user.recent_comments.each do |comment| %>
                <div class="comment-container">
                    <div class="commenter-image-cropper">
                        <%= link_to user_path(comment.user) do %>
                            <img src="<%= comment.user.image_url %>" class="commenter-image">
                        <% end  %>
                    </div>
                    <div class="comment-content-wrapper">
                        <div class="commenter">
                            <%= link_to comment.user.username, user_path(comment.user) %></h2>
                        </div>
                        <div class="comment">
                            <p><%= comment.content %></p>
                        </div>
                        <div class="comment-date">
                            <p><em><%= comment.created_at.strftime("%B %d, %Y") %></em></p>
                        </div>
                    </div>
                </div>
                <%= button_to 'ViewPost', post_path(comment.post), method: :get, :class => "view_post_button" %></li>
            <% end %>
        <% else %>
            <p><%= @user.username %> hasn't made any commentsyet! </p>
        <% end %>
<div class="profile-footer">
    <p class="edit-profile"><%= link_to "Edit Profile",edit_user_path(@user), :method => 'get' %> </p>
    <p class='logout'> <%= link_to "Logout", logout_path,method: :delete %> </p>
<div>