config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, :supes, :products, :posts, :events, :comments, :sessions, :user_supes, :user_events, :charges
  resources :cart_products, only: [:create, :destroy]
  resources :purchases, only: [:show, :index]

  get '/home', to: 'users#home', as: 'user_home'
  get '/cart', to: 'users#my_cart', as: 'user_cart'
  post '/comments', to: 'comments#create'
  get '/', to: 'sessions#new', as: 'new_login'
  post '/', to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/confirmation', to: 'purchases#confirmation', as: 'confirmation'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :cart_products, dependent: :destroy
    has_many :products, through: :cart_products 
    has_one :purchase

    def has_items?
        self.products.count > 0
    end 

    def purchased?
        if self.purchase
            true
        else
            false
        end 
    end 
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :supe
    has_many :user_events, dependent: :destroy
    has_many :users, through: :user_events

    validates :title, :supe_id, :date, :cost, :location, presence: true
    validates :cost, numericality: {only_integers: true}
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :supe 
    has_one_attached :post_file 
    has_many :comments, dependent: :destroy

    def has_media?
        self.post_file.attached?
    end 

    def has_image?
        self.post_file.content_type.include?("image")
    end 
end

app/models/product.rb
class Product < ApplicationRecord
    validates_presence_of :name, :description, :price
    validates_uniqueness_of :name
    validates_numericality_of :price

    has_many :carts
    has_many :users, through: :carts


    def self.product_sort
        Product.all.sort_by { |product| product.price }
    end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :cart

  def to_param
    uuid
  end 
end

app/models/supe.rb
class Supe < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :events, dependent: :destroy

    validates_presence_of :name, :bio, :powers
    validates_uniqueness_of :name


    has_many :user_supes, dependent: :destroy
    has_many :users, through: :user_supes, dependent: :destroy
    has_many :products, dependent: :destroy
    has_many :events, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :comments, dependent: :destroy
    has_many :user_supes
    has_many :supes, through: :user_supes
    has_many :user_events, dependent: :destroy 
    has_many :events, through: :user_events

    has_many :comments, dependent: :destroy
    has_many :user_supes, dependent: :destroy
    has_many :supes, through: :user_supes
    has_many :carts
    has_many :products, through: :carts
    has_many :user_events, dependent: :destroy
    has_many :events, through: :user_events

    validates_presence_of :username, :password
    validates_uniqueness_of :username

    def following?(supe)
        self.supes.include?(supe)
    end

    def attending?(event)
        self.events.include?(event)
    end 

    def feed
        Post.all.filter {|post| self.supes.include?(post.supe)}.reverse
    end 

    def cart
        if self.carts.count == 0 || self.carts.last.purchase
            Cart.create(user: self)
        else
            self.carts.last
        end
    end 

    enum role: [:member, :admin]

    after_initialize do
        if self.new_record?
            self.role ||= :member
        end
    end

    def recent_comments
        recent_comments = self.comments.sort_by { |comment| comment.created_at }.reverse
        recent_comments.first(3)
    end
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/user_supe.rb
class UserSupe < ApplicationRecord
    belongs_to :user
    belongs_to :supe

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    after_action :verify_authorized, only: [:new, :create, :destroy]

    
    def index
        @posts = Post.all
    end 

    def new
        @post = Post.new
        authorize @post
    end 

    def show
        @post = Post.find(params[:id])
        @comment = Comment.new
    end 

    def create
        @post = Post.create(post_params)
        authorize @post
        redirect_to supe_path(@post.supe)
    end 

    def update
        @post = Post.find(params[:id])
        @post.update(likes: (@post.likes + 1))
        redirect_back fallback_location: user_home_path
    end 

    private

    def post_params
        params.require(:post).permit(:supe_id, :content, :likes, :post_file)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/supes_helper.rb
module SupesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Mod2Project080320</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">
    </head>

    <body>
        <div class="container px-5">
            <div class="row banner mx-5">
                <img src="<%= asset_path('supe-social-logo.png') %>" class="banner-img">
            </div>
            <div class="row mt-3 mx-5">
                <div class="col-3 left-panel">
                    <% if @current_user %>
                        <div class="bg-light p-2">
                        <h1 class="profile-name"><%= @current_user.username %></h1>
                        <%= link_to user_path(@current_user) do %>
                            <img src="<%= @current_user.image_url %>" class="profile-img">
                        <% end %>
                        <ul class="user-nav">
                            <li><%= link_to "My Profile", user_path(@current_user) %></li>
                            <li><%= link_to "Home", user_home_path%></li>
                            <li><%= link_to "The Seven", supes_path %></li>
                            <li><%= link_to "Merchandise", products_path %></li>
                            <li><%= link_to "Events", events_path %></li>
                            <li><%= link_to "My Cart", user_cart_path %></li>
                        </ul>
                        <% if @current_user.role == "admin" %>
                            <ul class="user-nav">
                                <!--<li><%= link_to "Create Post", new_post_path %></li> -->
                                <li><%= link_to "Create Event", new_event_path %></li>
                                <li><%= link_to "List Product", new_product_path %></li>
                            </ul>
                        <% end %>
                        <ul class="user-nav">
                            <li><%= link_to "Logout", logout_path, method: :delete %></li>
                        </ul>
                    <% end %>
                    </div>
                </div>
                <div class="col-9">
                    <div class="p-2 bg-light">
                    <%= yield %>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://checkout.stripe.com/checkout.js"></script>
    </body>
</html>